# Generated by Django 5.1.3 on 2024-12-10 03:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('ci1', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_ci', message='El campo debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('nombre', models.CharField(choices=[('1', 'Artículos publicados en revistas de las bases de datos Scopus o Web of Science'), ('2', 'Artículos publicados en revistas de las bases de datos regionales'), ('3', 'Actas de congresos indexados (Proceedings)'), ('4', 'Libros y capítulos'), ('5', 'Proyectos de Investigación'), ('6', 'Proyectos de Vinculación con la sociedad')], max_length=50, verbose_name='Tipo de Documento')),
                ('filiacion_UEP', models.CharField(default='', max_length=100)),
                ('titulo', models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('nombre_revista', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Base_datos', models.CharField(default='', max_length=200)),
                ('Año_Base_datos', models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_date', message='El campo debe contener exactamente 4 dígitos numéricos.', regex='^\\d{4}$')])),
                ('nombre_evento_o_compendio', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Editorial', models.CharField(default='', max_length=100)),
                ('Filiacion_Autor_es', models.CharField(default='', max_length=100)),
                ('Codigo_ISSN', models.CharField(default='', max_length=100)),
                ('Codigo_ISBN', models.CharField(default='', max_length=100)),
                ('Año_Publiacion', models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_date', message='El campo debe contener exactamente 4 dígitos numéricos.', regex='^\\d{4}$')])),
                ('link_acceso', models.CharField(default='', max_length=300)),
                ('N_Registro_Senadi', models.CharField(default='', max_length=100)),
                ('Exposicion_Procendings', models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='NA', max_length=20, null=True)),
                ('Revision_pares', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentación que evidencie los procesos de revisión por pares')),
                ('Revision_externos', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentación que evidencie los procesos de revisión por Externos')),
                ('Evidencia_Nacional', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentos que evidencien que la obra fue expuesta eventos, exposiciones nacionales ')),
                ('Evidencia_Internacional', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentos que evidencien que la obra fue expuesta eventos, exposiciones Internacionales')),
                ('Evidencia_Propiedad_Intelectual', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentos que evidencien que evidencien la propiedad intelectual reportada')),
                ('Registro_SENADI', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Registro de propiedad intelectual en el SENADI')),
                ('Certificados_Exposiciones', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Certificados/permisos de exposiciones en eventos nacionales e internacionales')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Academico',
            fields=[
                ('ci', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ci', message='El campo debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('Primer_nombre', models.CharField(default='', max_length=100)),
                ('Segundo_nombre', models.CharField(default='', max_length=100)),
                ('primer_apellido', models.CharField(default='', max_length=100)),
                ('segundo_apellido', models.CharField(default='', max_length=100)),
                ('fecha_nacimiento', models.DateField(default=datetime.date(2000, 1, 1))),
                ('genero', models.CharField(default='', max_length=100)),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Viudo/a', 'Viudo/a'), ('Divorciado/a', 'Divorciado/a'), ('Unión de Hecho', 'Unión de Hecho')], default='Soltero/a', max_length=20)),
                ('correo_institucional', models.EmailField(default='default@uce.edu.com', max_length=254, unique=True)),
                ('telefono_contacto', models.CharField(default='', max_length=10)),
                ('asignaturas_impartidas', models.TextField(default='')),
                ('programa_educativo', models.CharField(choices=[('Pregrado', 'Pregrado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='Pregrado', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('Tiempo total', 'Tiempo total'), ('Tiempo parcial', 'Tiempo parcial')], default='Tiempo total', max_length=20)),
            ],
        ),
    ]
