# Generated by Django 5.1.3 on 2025-01-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_academico',
            old_name='carrera',
            new_name='carrera_personal',
        ),
    ]
