# Generated by Django 5.1.3 on 2024-12-10 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_Libros_Capitulos',
            fields=[
                ('ci1', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_ci', message='El campo debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='CI')),
                ('titulo', models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documento',
            name='ci1',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_ci', message='El campo debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='CI'),
        ),
    ]
