# Generated by Django 5.1.3 on 2025-01-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador20',
            old_name='carrera',
            new_name='carrera_Indicador20',
        ),
    ]
