# Generated by Django 5.1.3 on 2024-12-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0002_documentos_libros_capitulos_alter_documento_ci1'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='Estado',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Parcial', 'Parcial')], default='Completo: Libro, Parcial: Capítulo', max_length=20),
        ),
    ]
