# Generated by Django 5.1.3 on 2025-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0002_rename_carrera_indicador20_carrera_indicador20'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name_plural': 'Fuentes de Información: Contribución de la investigación a la carrera'},
        ),
        migrations.AlterField(
            model_name='personal_academico',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='', max_length=100),
        ),
    ]
