# Generated by Django 5.1.3 on 2024-12-10 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0003_documentos_libros_capitulos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='Año_Publiacion',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_date', message='El campo debe contener exactamente 4 dígitos numéricos.', regex='^\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='Codigo_ISBN',
            field=models.CharField(default='', max_length=100, verbose_name='Código ISBN'),
        ),
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='Editorial',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='Link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='N_Cap',
            field=models.CharField(default='', max_length=100, verbose_name='Capítulos Concluidos'),
        ),
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='T_Cap',
            field=models.CharField(default='', max_length=100, verbose_name='Capítulos Totales'),
        ),
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='filiacion_Autores',
            field=models.CharField(default='', max_length=100, verbose_name='Filiación de Autores'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(default='', max_length=400, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentos_libros_capitulos',
            name='Estado',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Parcial', 'Parcial')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentos_libros_capitulos',
            name='titulo',
            field=models.CharField(default='', max_length=400, primary_key=True, serialize=False, unique=True),
        ),
    ]
