# Generated by Django 5.1.3 on 2024-12-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0004_documentos_libros_capitulos_año_publiacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='Revision_externos',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentación que evidencie los procesos de revisión por Externos'),
        ),
        migrations.AddField(
            model_name='documentos_libros_capitulos',
            name='Revision_pares',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentación que evidencie los procesos de revisión por pares'),
        ),
    ]
