# Generated by Django 5.1.3 on 2024-12-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0005_documentos_libros_capitulos_revision_externos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentos_Libros_Capitulos',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Evidencia_Propiedad_Intelectual',
        ),
        migrations.AddField(
            model_name='documento',
            name='Estado',
            field=models.CharField(choices=[('Libro Total', 'Libro Total'), ('Libro Parcial', 'Libro Parcial')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='N_Cap_Par',
            field=models.CharField(default='', max_length=100, verbose_name='Capítulos Desarrollados por el Autor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='T_Cap',
            field=models.CharField(default='', max_length=100, verbose_name='Capítulos Totales desarrollados por el Autor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Registro_SENADI',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Certificado de registro de propiedad intelectual en el SENADI'),
        ),
    ]
