# Generated by Django 5.1.3 on 2024-12-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0006_delete_documentos_libros_capitulos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Base_datos',
            field=models.CharField(default='No Aplica', max_length=200),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Editorial',
            field=models.CharField(default='No Aplica', max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Estado',
            field=models.CharField(choices=[('Libro Total', 'Libro Total'), ('Libro Parcial', 'Libro Parcial')], default='No Aplica', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='N_Cap_Par',
            field=models.IntegerField(blank=True, default='0', max_length=100, null=True, verbose_name='Capítulos Desarrollados por el Autor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='T_Cap',
            field=models.IntegerField(blank=True, default='0', max_length=100, null=True, verbose_name='Capítulos Totales desarrollados por el Autor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_evento_o_compendio',
            field=models.CharField(blank=True, default='No Aplica', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_revista',
            field=models.CharField(blank=True, default='No Aplica', max_length=200, null=True),
        ),
    ]
