# Generated by Django 5.1.3 on 2024-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0008_alter_documento_n_cap_par_alter_documento_t_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='N_Cap_Par',
            field=models.IntegerField(blank=True, default='0', verbose_name='Capítulos Desarrollados por el Autor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='T_Cap',
            field=models.IntegerField(blank=True, default='0', verbose_name='Capítulos Totales desarrollados por el Autor'),
        ),
    ]
