# Generated by Django 5.1.3 on 2024-12-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0009_alter_documento_n_cap_par_alter_documento_t_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Areas_Niveles',
            field=models.CharField(choices=[('1', 'Obtenciones Vegetales y Conocimientos Tradicionales'), ('2', 'Derechos de Autor y Conexos'), ('3', 'Propiedad Industrial')], default='No Aplica', max_length=20),
        ),
    ]
