# Generated by Django 5.1.3 on 2024-12-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0011_alter_documento_areas_niveles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_academico',
            name='tipo_contrato',
            field=models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Tiempo Parcial', 'Tiempo Parcial')], default='Tiempo total', max_length=20),
        ),
    ]
