# Generated by Django 5.1.3 on 2024-12-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0012_alter_personal_academico_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(choices=[('Artculos Scopus o Web of Science', 'Artículos publicados en revistas de bases de datos Scopus o Web of Science'), ('Artículos bases de datos regionales', 'Artículos publicados en revistas de bases de datos regionales'), ('Proceedings', 'Actas de congresos indexados (Proceedings)'), ('Libros y capítulos', 'Libros y capítulos'), ('Proyectos de Investigación', 'Proyectos de Investigación'), ('Proyectos de Vinculación con la sociedad', 'Proyectos de Vinculación con la sociedad')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
