# Generated by Django 5.1.3 on 2024-12-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0013_alter_documento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Estado',
            field=models.CharField(choices=[('Libro Total', 'Libro Total'), ('Libro Parcial', 'Libro Parcial'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=20),
        ),
    ]
