# Generated by Django 5.1.3 on 2024-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0014_alter_documento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Areas_Niveles',
            field=models.CharField(choices=[('Obtenciones Vegetales y Conocimientos Tradicionales', 'Obtenciones Vegetales y Conocimientos Tradicionales'), ('Derechos de Autor y Conexos', 'Derechos de Autor y Conexos'), ('Propiedad Industrial', 'Propiedad Industrial'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Exposicion_Procendings',
            field=models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional'), ('No Aplica', 'No Aplica')], default='NA', max_length=20, null=True),
        ),
    ]
