# Generated by Django 5.1.3 on 2024-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0015_alter_documento_areas_niveles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='carrera',
            field=models.CharField(choices=[('Geología', 'Geología'), ('Minas', 'Minas'), ('Petróleos', 'Petróleos'), ('Ambiental', 'Ambiental')], default='No Aplica', max_length=20),
        ),
    ]
