# Generated by Django 5.1.3 on 2024-12-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0016_documento_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Funciones_Sustantivas', models.CharField(choices=[('Docencia', 'Docencia'), ('Investigación e Innovación', 'Investigación e Innovación'), ('Docencia', 'Docencia')], max_length=50, verbose_name='Funciones Sustantivas')),
            ],
        ),
    ]
