# Generated by Django 5.1.3 on 2024-12-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0017_indicador20'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador20',
            name='Evidencia_Nacional',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Documentación que evidencie la planificación y ejecución de los programas o proyectos interdisciplinares'),
        ),
    ]
