# Generated by Django 5.1.3 on 2024-12-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0018_indicador20_evidencia_nacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador20',
            name='carrera',
            field=models.CharField(choices=[('Geología', 'Geología'), ('Minas', 'Minas'), ('Petróleos', 'Petróleos'), ('Ambiental', 'Ambiental')], default='No Aplica', max_length=20),
        ),
    ]
