# Generated by Django 5.1.3 on 2024-12-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0020_remove_indicador20_evidencia_nacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador20',
            name='autores',
            field=models.CharField(default='', max_length=300, verbose_name='Autores del Proyecto o Programa'),
        ),
        migrations.AddField(
            model_name='indicador20',
            name='nombre',
            field=models.CharField(default='', max_length=300, verbose_name='Nombre del Proyecto o Programa'),
        ),
    ]
