# Generated by Django 5.1.3 on 2024-12-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0021_indicador20_autores_indicador20_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador20',
            old_name='Planificación_Proyectos_Programas',
            new_name='Planificaciopn_Proyectos_Programas',
        ),
    ]
