# Generated by Django 5.1.3 on 2024-12-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0022_rename_planificación_proyectos_programas_indicador20_planificaciopn_proyectos_programas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name_plural': 'Fuentes de Información: Indicador 19'},
        ),
        migrations.AlterModelOptions(
            name='indicador20',
            options={'verbose_name_plural': 'Fuentes de Información: Indicador 20'},
        ),
        migrations.AlterModelOptions(
            name='personal_academico',
            options={'verbose_name_plural': 'Lista Personal Academico'},
        ),
        migrations.AddField(
            model_name='personal_academico',
            name='carrera',
            field=models.CharField(choices=[('Geología', 'Geología'), ('Minas', 'Minas'), ('Petróleos', 'Petróleos'), ('Ambiental', 'Ambiental')], default='No Aplica', max_length=20),
        ),
    ]
