# Generated by Django 5.1.3 on 2024-12-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0023_alter_documento_options_alter_indicador20_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_academico',
            name='nombramiento',
            field=models.CharField(choices=[('Nombramiento definitivo', 'Nombramiento definitivo'), ('Nombramiento provisional', 'Nombramiento provisional'), ('Contrato', 'Contrato')], default='Pregrado', max_length=50),
        ),
    ]
